baseURL = 'https://xiaopacaipro.github.io/nwesite/'
languageCode = 'en-us'
title = '看见金城兰州'
theme = 'ananke'
publishDir = "docs"
canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true